"""US-specific adapters, targets, and pipelines for microplex."""

from microplex.targets import TargetSet, TargetSpec

from microplex_us.calibration_harness import (
    CalibrationHarness,
    CalibrationResult,
    run_pe_parity_suite,
)
from microplex_us.cps_synthetic import (
    CPSSummaryStats,
    CPSSyntheticGenerator,
    validate_synthetic,
)
from microplex_us.data import (
    create_sample_data,
    get_data_info,
    load_cps_asec,
    load_cps_for_synthesis,
)
from microplex_us.geography import (
    BLOCK_LEN,
    COUNTY_LEN,
    STATE_LEN,
    TRACT_LEN,
    BlockGeography,
    derive_geographies,
    load_block_probabilities,
    normalize_us_state_fips,
)
from microplex_us.hierarchical import prepare_cps_for_hierarchical
from microplex_us.pe_targets import (
    PETargets,
    create_calibration_targets,
    get_pe_targets,
)
from microplex_us.pipelines import (
    FrontierMetric,
    USHouseholdTargetReweightingResult,
    USMicroplexArtifactPaths,
    USMicroplexBuildConfig,
    USMicroplexBuildResult,
    USMicroplexExperimentReport,
    USMicroplexExperimentResult,
    USMicroplexPerformanceHarnessConfig,
    USMicroplexPerformanceHarnessRequest,
    USMicroplexPerformanceHarnessResult,
    USMicroplexPerformanceSession,
    USMicroplexPipeline,
    USMicroplexRunRegistryEntry,
    USMicroplexSourceExperimentSpec,
    USMicroplexTargets,
    USMicroplexVersionedBuildArtifacts,
    append_us_microplex_run_index_entry,
    append_us_microplex_run_registry_entry,
    build_and_save_versioned_us_microplex,
    build_and_save_versioned_us_microplex_from_data_dir,
    build_and_save_versioned_us_microplex_from_source_provider,
    build_and_save_versioned_us_microplex_from_source_providers,
    build_us_microplex,
    build_us_microplex_run_registry_entry,
    build_us_microplex_site_snapshot,
    compare_us_microplex_target_delta_rows,
    default_us_source_mix_experiments,
    list_us_microplex_target_delta_rows,
    load_us_microplex_run_registry,
    rebuild_us_microplex_run_index,
    resolve_us_microplex_frontier_artifact_dir,
    resolve_us_microplex_run_index_path,
    reweight_us_household_targets,
    run_us_microplex_performance_harness,
    run_us_microplex_source_experiments,
    save_us_microplex_artifacts,
    save_versioned_us_microplex_artifacts,
    save_versioned_us_microplex_build_result,
    select_us_microplex_frontier_entry,
    select_us_microplex_frontier_index_row,
    warm_us_microplex_parity_cache,
    write_us_microplex_site_snapshot,
)
from microplex_us.policyengine import (
    PolicyEngineUSComparisonCache,
    PolicyEngineUSConstraint,
    PolicyEngineUSDBTarget,
    PolicyEngineUSDBTargetProvider,
    PolicyEngineUSEntityTableBundle,
    PolicyEngineUSMicrosimulationAdapter,
    PolicyEngineUSQuantityTarget,
    PolicyEngineUSTargetComparisonReport,
    PolicyEngineUSTargetEvaluation,
    PolicyEngineUSTargetEvaluationReport,
    PolicyEngineUSVariableBinding,
    build_policyengine_us_time_period_arrays,
    compare_policyengine_us_target_query_to_baseline,
    compile_policyengine_us_household_linear_constraints,
    compute_policyengine_us_definition_hash,
    detect_policyengine_pseudo_inputs,
    evaluate_policyengine_us_target_query,
    evaluate_policyengine_us_target_set,
    filter_supported_policyengine_us_targets,
    infer_policyengine_us_variable_bindings,
    load_policyengine_us_entity_tables,
    materialize_policyengine_us_variables,
    policyengine_us_variables_to_materialize,
    project_frame_to_time_period_arrays,
    write_policyengine_us_time_period_dataset,
)
from microplex_us.source_registry import (
    DEFAULT_SOURCE_VARIABLE_POLICIES,
    PUF_SOURCE_VARIABLE_POLICY,
    SourceVariablePolicy,
    SourceVariablePolicySpec,
    resolve_source_variable_capabilities,
)
from microplex_us.target_registry import (
    TargetCategory,
    TargetGroup,
    TargetLevel,
    TargetRegistry,
    get_registry,
    print_registry_summary,
)
from microplex_us.targets import (
    POLICYENGINE_US_COUNT_ENTITIES,
    policyengine_db_target_to_canonical_spec,
    policyengine_db_targets_to_canonical_set,
)
from microplex_us.unified_calibration import (
    CalibrationTarget,
    UnifiedCalibrator,
    calibrate_to_pe_targets,
)

try:
    from microplex_us.validation import (
        AGI_BRACKETS,
        FILING_STATUSES,
        BaselineComparison,
        MetricComparison,
        SOITargets,
        ValidationResult,
        compute_baseline_comparison,
        compute_validation_metrics,
        export_comparison_json,
        get_soi_years,
        load_soi_targets,
        validate_against_soi,
    )
except ModuleNotFoundError as exc:
    if exc.name != "polars":
        raise

    AGI_BRACKETS = None
    FILING_STATUSES = None
    BaselineComparison = None
    MetricComparison = None
    SOITargets = None
    ValidationResult = None
    compute_baseline_comparison = None
    compute_validation_metrics = None
    export_comparison_json = None
    get_soi_years = None
    load_soi_targets = None
    validate_against_soi = None

__all__ = [
    "CalibrationHarness",
    "CalibrationResult",
    "run_pe_parity_suite",
    "PETargets",
    "create_calibration_targets",
    "get_pe_targets",
    "USMicroplexArtifactPaths",
    "FrontierMetric",
    "USMicroplexRunRegistryEntry",
    "USMicroplexBuildConfig",
    "USMicroplexBuildResult",
    "USMicroplexPipeline",
    "append_us_microplex_run_index_entry",
    "append_us_microplex_run_registry_entry",
    "compare_us_microplex_target_delta_rows",
    "USMicroplexTargets",
    "USMicroplexVersionedBuildArtifacts",
    "USMicroplexExperimentReport",
    "USMicroplexExperimentResult",
    "USMicroplexSourceExperimentSpec",
    "USMicroplexPerformanceHarnessConfig",
    "USMicroplexPerformanceHarnessRequest",
    "USMicroplexPerformanceHarnessResult",
    "USMicroplexPerformanceSession",
    "USHouseholdTargetReweightingResult",
    "default_us_source_mix_experiments",
    "build_and_save_versioned_us_microplex",
    "build_and_save_versioned_us_microplex_from_data_dir",
    "build_and_save_versioned_us_microplex_from_source_provider",
    "build_and_save_versioned_us_microplex_from_source_providers",
    "build_us_microplex",
    "build_us_microplex_run_registry_entry",
    "load_us_microplex_run_registry",
    "list_us_microplex_target_delta_rows",
    "rebuild_us_microplex_run_index",
    "reweight_us_household_targets",
    "resolve_us_microplex_frontier_artifact_dir",
    "resolve_us_microplex_run_index_path",
    "run_us_microplex_performance_harness",
    "run_us_microplex_source_experiments",
    "save_us_microplex_artifacts",
    "save_versioned_us_microplex_build_result",
    "build_us_microplex_site_snapshot",
    "select_us_microplex_frontier_index_row",
    "save_versioned_us_microplex_artifacts",
    "select_us_microplex_frontier_entry",
    "write_us_microplex_site_snapshot",
    "warm_us_microplex_parity_cache",
    "PolicyEngineUSConstraint",
    "PolicyEngineUSComparisonCache",
    "PolicyEngineUSDBTarget",
    "PolicyEngineUSDBTargetProvider",
    "PolicyEngineUSEntityTableBundle",
    "PolicyEngineUSMicrosimulationAdapter",
    "PolicyEngineUSQuantityTarget",
    "PolicyEngineUSTargetComparisonReport",
    "PolicyEngineUSTargetEvaluation",
    "PolicyEngineUSTargetEvaluationReport",
    "PolicyEngineUSVariableBinding",
    "build_policyengine_us_time_period_arrays",
    "compare_policyengine_us_target_query_to_baseline",
    "compile_policyengine_us_household_linear_constraints",
    "compute_policyengine_us_definition_hash",
    "detect_policyengine_pseudo_inputs",
    "evaluate_policyengine_us_target_query",
    "evaluate_policyengine_us_target_set",
    "filter_supported_policyengine_us_targets",
    "infer_policyengine_us_variable_bindings",
    "load_policyengine_us_entity_tables",
    "materialize_policyengine_us_variables",
    "policyengine_us_variables_to_materialize",
    "project_frame_to_time_period_arrays",
    "write_policyengine_us_time_period_dataset",
    "SourceVariablePolicy",
    "SourceVariablePolicySpec",
    "PUF_SOURCE_VARIABLE_POLICY",
    "DEFAULT_SOURCE_VARIABLE_POLICIES",
    "resolve_source_variable_capabilities",
    "CalibrationTarget",
    "UnifiedCalibrator",
    "calibrate_to_pe_targets",
    "CPSSummaryStats",
    "CPSSyntheticGenerator",
    "validate_synthetic",
    "load_cps_asec",
    "load_cps_for_synthesis",
    "create_sample_data",
    "get_data_info",
    "BlockGeography",
    "load_block_probabilities",
    "derive_geographies",
    "normalize_us_state_fips",
    "prepare_cps_for_hierarchical",
    "STATE_LEN",
    "COUNTY_LEN",
    "TRACT_LEN",
    "BLOCK_LEN",
    "TargetRegistry",
    "TargetSpec",
    "TargetSet",
    "TargetCategory",
    "TargetLevel",
    "TargetGroup",
    "get_registry",
    "print_registry_summary",
    "POLICYENGINE_US_COUNT_ENTITIES",
    "policyengine_db_target_to_canonical_spec",
    "policyengine_db_targets_to_canonical_set",
    "AGI_BRACKETS",
    "FILING_STATUSES",
    "SOITargets",
    "get_soi_years",
    "load_soi_targets",
    "compute_validation_metrics",
    "ValidationResult",
    "validate_against_soi",
    "MetricComparison",
    "BaselineComparison",
    "compute_baseline_comparison",
    "export_comparison_json",
]
